#Compose file (dev par defaut)

services:
  api:
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - '${API_PORT:-3000}:3000' # API server
      - '${DEBUG_PORT:-9229}:9229' # Node.js debugger
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app
  db:
    image: mariadb
    restart: always
    user: root
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=${PROD_MARIADB_ROOT_PASSWORD_FILE}
      - MARIADB_DATABASE=${PROD_MARIADB_DATABASE}
    expose:
      - 3306
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt

networks:
  api-network:
    name: api-network
    driver: bridge